### ISSUE TITLE
spazi multipli

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/iterazione_c#12]
hai caricato anche l'eseguibile

metti la tabella degli stati come commento

**Comment by TeoColuccio** [comment]
Prof ho risolto

**Comment by FabioZTessitore** [comment]
hai solo aggiustato il gitignore. Nella repository è ancora presente l'eseguibile e la tabella degli stati non c'è

**Comment by TeoColuccio** [comment]
Ora c'è la tabella... era stata aggiunta ad un altro file

**Comment by FabioZTessitore** [comment]
il codice non coincide con la tabella

ps. per gli stati invece di usare 0 e 1 metti dei nomi con enum
