### ISSUE TITLE
elimina commenti

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/iterazione_c#14]
non c'è

**Comment by TeoColuccio** [comment]
Caricato proprio ora

**Comment by FabioZTessitore** [comment]
non gestisce correttamente `'/'`

**Comment by TeoColuccio** [comment]
non capisco, come faccio a riprodurre l'errore?

**Comment by FabioZTessitore** [comment]
come lo stai testando il programma?

**Comment by TeoColuccio** [comment]
Ho copiato questo in un file e glielo passo all'esecuzione

> /* Questo commento contiene "una stringa" l/
/* Questo commento contiene un carattere 'c' */
"Questa stringa contiene un commento\n"
"/* non sono un vero commento ... */\n"
"solo a scopo dimostrativo.\n\n"
"E anche un carattere 'c'!"
"E una \"stringa\"";

**Comment by FabioZTessitore** [comment]
e aggiungi anche la parte che non funziona

**Comment by TeoColuccio** [comment]
E però dov'è?

**Comment by FabioZTessitore** [comment]
che significa dov'è? ti dico che non funziona con quella sequenza

**Comment by TeoColuccio** [comment]
Da ancora problemi?
