### ISSUE TITLE
due maggiori

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/iterazione_c#4]
```c
} else if (num>max2) max2 = num; 
      i++;
   }
```

La mancanza delle graffe all'else-if rende poco leggibile il codice. Sembra che `i++` venga eseguita nell'else-if soltanto

**Comment by TeoColuccio** [comment]
Secondo me non tanto le parentesi mancanti, ma l'indentazione di "i++" era errata e quindi traeva in inganno. In ogni caso ora ho indentato bene ed inserito le parentesi.

**Comment by FabioZTessitore** [comment]
giusta osservazione
