### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/iterazione_c#5]
manca, come stai compilando?

**Comment by TeoColuccio** [comment]
Eh con il solito gcc  da terminale..

**Comment by FabioZTessitore** [comment]
qui devi iniziare ad usare make con un semplice makefile

**Comment by TeoColuccio** [comment]
Giusto.. però il fatto che dopo "make", nel terminale, se premo tab non mi chiama nulla non mi piace molto. Non possiamo risolvere aggiungendo istruzioni specifiche?

**Comment by FabioZTessitore** [comment]
il file dovrebbe avere iniziale maiuscola (Makefile)

per il momento non aggiungere niente, più avanti scriverai solo make
