### ISSUE TITLE
quadrato

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/iterazione_c#6]
aggiorna il gitignore

**Comment by TeoColuccio** [comment]
Fatto. Certo che non vi sfugge niente hahah...

**Comment by FabioZTessitore** [comment]
non fare l'input del carattere e usa int invece di char (quando si lavora con un singolo carattere è meglio).
Poi aggiusta le variabili nei cicli come abbiamo visto negli altri esercizi

**Comment by TeoColuccio** [comment]
Per quanto riguarda le variabili, ho spostato solo l'azzeramento di J, in quanto l'inizializzazione vera e propria delle variabili l'abbiamo sempre fatta all'inizio... voi che dite? Meglio spostare anche quei i=0 e j=0?

**Comment by FabioZTessitore** [comment]
se stanno vicini alla condizione è meglio, risulta più chiaro
