### ISSUE TITLE
occorrenze cifra

### ISSUE THREAD

**Issue by FabioZTessitore** [TeoColuccio/iterazione_c#8]
se il file si chiama cifra.c e nel gitignore hai scritto occorrenze_cifra che devo pensare? che non stai usando make per la compilazione

**Comment by TeoColuccio** [comment]
Ora correggo.. però uso sempre make. Non ha visto alcun "cifra" perché, presente o meno nel .gitignore, sono attento a rimuovere gli eseguibili manualmente prima di fare un push.
